-- Flags verified against `copilot --help`. --effort gained none and max;
-- --resume takes an optional session id, name, or ID prefix.
return require("harness.adapters._shared").raw_cli_adapter({
  name = "copilot",
  label = "  Copilot",
  cmd = "copilot",
  options_schema = {
    { name = "yolo", flag = "--yolo", kind = "toggle" },
    { name = "allow_all_tools", flag = "--allow-all-tools", kind = "toggle" },
    { name = "continue", flag = "--continue", kind = "toggle" },
    { name = "plan", flag = "--plan", kind = "toggle" },
    { name = "autopilot", flag = "--autopilot", kind = "toggle" },
    { name = "no_remote", flag = "--no-remote", kind = "toggle" },
    { name = "enable_memory", flag = "--enable-memory", kind = "toggle" },
    { name = "no_custom_instructions", flag = "--no-custom-instructions", kind = "toggle" },
    { name = "experimental", flag = "--experimental", kind = "toggle" },
    { name = "resume", flag = "--resume", kind = "opt_value", prompt = "Session ID, ID prefix, or name" },
    {
      name = "mode",
      flag = "--mode",
      kind = "enum",
      choices = { "interactive", "plan", "autopilot" },
    },
    {
      name = "effort",
      flag = "--effort",
      kind = "enum",
      choices = { "none", "low", "medium", "high", "xhigh", "max" },
    },
    {
      name = "context",
      flag = "--context",
      kind = "enum",
      choices = { "default", "long_context" },
    },
    {
      name = "log_level",
      flag = "--log-level",
      kind = "enum",
      choices = { "none", "error", "warning", "info", "debug", "all", "default" },
    },
    { name = "model", flag = "--model", kind = "value", prompt = "Model (or 'auto')" },
    { name = "agent", flag = "--agent", kind = "value", prompt = "Custom agent name" },
    { name = "name", flag = "--name", kind = "value", prompt = "Name for the new session" },
    { name = "session_id", flag = "--session-id", kind = "value", prompt = "Session or task ID" },
    { name = "add_dir", flag = "--add-dir", kind = "list", prompt = "Extra allowed dirs (comma-separated)" },
    { name = "allow_tool", flag = "--allow-tool", kind = "list", prompt = "Allowed tools (comma-separated)" },
    { name = "deny_tool", flag = "--deny-tool", kind = "list", prompt = "Denied tools (comma-separated)" },
    { name = "plugin_dir", flag = "--plugin-dir", kind = "list", prompt = "Plugin dirs (comma-separated)" },
  },
})
